version: "3.9"
services:
  olympic:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Polyakov_209"
      POSTGRES_USER: "Polyakov_209"
      POSTGRES_PASSWORD: "Polyakov_209"
    volumes:
      - ./library:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
