version: "3.9"
services:
  library:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Polyakov_209"
      POSTGRES_USER: "Polyakov_209"
      POSTGRES_PASSWORD: "Polyakov_209"
    volumes:
      - ./library:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  trains:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Polyakov_209"
      POSTGRES_USER: "Polyakov_209"
      POSTGRES_PASSWORD: "Polyakov_209"
    volumes:
      - ./trains:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  patients:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Polyakov_209"
      POSTGRES_USER: "Polyakov_209"
      POSTGRES_PASSWORD: "Polyakov_209"
    volumes:
      - ./patients:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
